spring:
  application:
    name: TX Process Dashboard
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8001
  
logging:
  level:
    root: INFO
    '[org.springframework]': INFO
    '[org.apache.kafka.clients.consumer.ConsumerConfig]': OFF
#    '[info.pushkaradhikari.beamline.custom]': DEBUG

txpd:
  result:
    location: ./output/
    enabled: true
  kafka-config:
    bootstrap-servers: localhost:9092
    topic: log_replay
    max-poll-records: 50
    auto-offset-reset: latest
    enable-auto-commit: false
    groups:
      miner: txpd-miner
      processor: txpd-processor
  influx-config:
    url: http://localhost:8086
    database: txpd-metrics
    username: admin
    password: adminpassword
